{ AltiumVerify.pas

  On-site verification that .PcbLib / .SchLib files generated by altium-designer-mcp
  open cleanly in a real Altium Designer install — the ground-truth check that the
  independent pyaltiumlib oracle only approximates.

  It reads a request file (one absolute library path per line) from the bridge
  directory, opens each library in Altium, and writes a JSON array of results to the
  response file. The PowerShell wrapper (..\Verify-Libraries.ps1) writes the request,
  launches this via Altium's RunScript CLI, and polls for the response.

  The RunScript launch mechanism and the file-based request/response bridge are
  adapted from coffeenmusic/altium-mcp (MIT) — https://github.com/coffeenmusic/altium-mcp

  Run via:
    X2.EXE -RScriptingSystem:RunScript(ProjectName="...\AltiumVerify.PrjScr"^|ProcName="AltiumVerify>Run")

  Limitation: a genuinely corrupt library can make Altium raise a modal
  "catastrophic failure" dialog that blocks the script (the try/except below only
  catches non-modal errors). That is itself a useful signal — if the wrapper times
  out waiting for the response, the file did not open. }

const
    BRIDGE_DIR = 'C:\Users\Public\altium_designer_mcp\';

// Escapes a string for embedding in JSON (paths contain backslashes).
function JsonEscape(const S : String) : String;
begin
    Result := StringReplace(S, '\', '\\', REPLACEALL);
    Result := StringReplace(Result, '"', '\"', REPLACEALL);
end;

procedure Run;
var
    RequestFile, ResponseFile : String;
    Requests, Response : TStringList;
    Json, Path, Ext, Kind, Detail : String;
    i, Emitted : Integer;
    Doc : IServerDocument;
    Opened : Boolean;
begin
    RequestFile  := BRIDGE_DIR + 'verify_request.txt';
    ResponseFile := BRIDGE_DIR + 'verify_response.json';
    if not DirectoryExists(BRIDGE_DIR) then ForceDirectories(BRIDGE_DIR);

    Requests := TStringList.Create;
    Response := TStringList.Create;
    try
        if not FileExists(RequestFile) then
        begin
            Response.Text := '{"error":"no request file at ' + JsonEscape(RequestFile) + '"}';
            Response.SaveToFile(ResponseFile);
            Exit;
        end;
        Requests.LoadFromFile(RequestFile);

        Json := '[';
        Emitted := 0;
        for i := 0 to Requests.Count - 1 do
        begin
            Path := Trim(Requests[i]);
            if Path = '' then Continue;

            Ext := UpperCase(ExtractFileExt(Path));
            if      Ext = '.PCBLIB' then Kind := 'PCBLIB'
            else if Ext = '.SCHLIB' then Kind := 'SCHLIB'
            else                         Kind := '';

            Opened := False;
            Detail := '';

            if not FileExists(Path) then
                Detail := 'file not found'
            else if Kind = '' then
                Detail := 'unsupported extension (expected .PcbLib or .SchLib)'
            else
            begin
                try
                    Doc := Client.OpenDocument(Kind, Path);
                    if Doc <> nil then
                    begin
                        Client.ShowDocument(Doc);
                        Opened := True;
                        Detail := 'opened';
                        Client.CloseDocument(Doc);
                    end
                    else
                        Detail := 'Altium OpenDocument returned nil (could not parse)';
                except
                    Opened := False;
                    Detail := 'exception while opening (likely catastrophic failure)';
                end;
            end;

            if Emitted > 0 then Json := Json + ',';
            Json := Json + '{"file":"' + JsonEscape(Path) + '","kind":"' + Kind + '","opened":';
            if Opened then Json := Json + 'true' else Json := Json + 'false';
            Json := Json + ',"detail":"' + JsonEscape(Detail) + '"}';
            Inc(Emitted);
        end;
        Json := Json + ']';

        Response.Text := Json;
        Response.SaveToFile(ResponseFile);
    finally
        Requests.Free;
        Response.Free;
    end;
end;
