//! Property-based no-panic tests for the binary parsers.
//!
//! The `PcbLib`/`SchLib` readers perform offset arithmetic on untrusted file
//! bytes. These tests prove the public entry points return `Err` — never
//! panic — on malformed, truncated, or mutated inputs.
//!
//! Purely random bytes are rejected early by the OLE (cfb) container and never
//! reach the Altium stream parsers, so the most valuable cases mutate a *valid*
//! library: the OLE container still parses, and the corrupted stream bytes are
//! actually fed to the Altium parsers.

use std::io::Cursor;
use std::sync::OnceLock;

use altium_designer_mcp::altium::pcblib::{Footprint, Pad, PcbLib};
use altium_designer_mcp::altium::schlib::{Pin, PinOrientation, SchLib, Symbol};

/// Builds a minimal but valid `.SchLib` and returns its raw bytes (cached).
fn valid_schlib_bytes() -> &'static [u8] {
    static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
    BYTES.get_or_init(|| {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("seed.SchLib");
        let mut lib = SchLib::new();
        let mut sym = Symbol::new("R");
        sym.add_pin(Pin::new("1", "1", -20, 0, 10, PinOrientation::Left));
        sym.add_pin(Pin::new("2", "2", 20, 0, 10, PinOrientation::Right));
        lib.add(sym);
        lib.save(&path).expect("save seed schlib");
        std::fs::read(&path).expect("read seed schlib")
    })
}

/// Builds a minimal but valid `.PcbLib` and returns its raw bytes (cached).
fn valid_pcblib_bytes() -> &'static [u8] {
    static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
    BYTES.get_or_init(|| {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("seed.PcbLib");
        let mut lib = PcbLib::new();
        let mut fp = Footprint::new("R0402");
        fp.add_pad(Pad::smd("1", -0.5, 0.0, 0.6, 0.5));
        fp.add_pad(Pad::smd("2", 0.5, 0.0, 0.6, 0.5));
        lib.add(fp);
        lib.save(&path).expect("save seed pcblib");
        std::fs::read(&path).expect("read seed pcblib")
    })
}

/// Applies the generated byte mutations and optional truncation to a copy of
/// the seed bytes.
fn mutate(
    seed: &[u8],
    muts: &[(proptest::sample::Index, u8)],
    truncate: Option<proptest::sample::Index>,
) -> Vec<u8> {
    let mut bytes = seed.to_vec();
    for (idx, val) in muts {
        let pos = idx.index(bytes.len());
        bytes[pos] = *val;
    }
    if let Some(t) = truncate {
        let len = t.index(bytes.len() + 1);
        bytes.truncate(len);
    }
    bytes
}

proptest::proptest! {
    /// Purely random bytes must never panic (rejected at the OLE layer).
    #[test]
    fn schlib_read_random_bytes_never_panics(
        bytes in proptest::collection::vec(proptest::prelude::any::<u8>(), 0..4096)
    ) {
        let _ = SchLib::read(Cursor::new(bytes));
    }

    /// A valid OLE container with mutated/truncated stream bytes must never
    /// panic in the Altium stream parsers — only `Ok` or `Err`.
    #[test]
    fn schlib_read_mutated_valid_never_panics(
        muts in proptest::collection::vec(
            (proptest::prelude::any::<proptest::sample::Index>(), proptest::prelude::any::<u8>()),
            0..64,
        ),
        truncate in proptest::prelude::any::<Option<proptest::sample::Index>>(),
    ) {
        let bytes = mutate(valid_schlib_bytes(), &muts, truncate);
        let _ = SchLib::read(Cursor::new(bytes));
    }

    /// Purely random bytes written to a file must never panic in `PcbLib::open`.
    #[test]
    fn pcblib_open_random_bytes_never_panics(
        bytes in proptest::collection::vec(proptest::prelude::any::<u8>(), 0..4096)
    ) {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("fuzz.PcbLib");
        std::fs::write(&path, &bytes).expect("write fuzz bytes");
        let _ = PcbLib::open(&path);
    }

    /// A valid OLE container with mutated/truncated stream bytes must never
    /// panic in `PcbLib::open`.
    #[test]
    fn pcblib_open_mutated_valid_never_panics(
        muts in proptest::collection::vec(
            (proptest::prelude::any::<proptest::sample::Index>(), proptest::prelude::any::<u8>()),
            0..64,
        ),
        truncate in proptest::prelude::any::<Option<proptest::sample::Index>>(),
    ) {
        let bytes = mutate(valid_pcblib_bytes(), &muts, truncate);
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("fuzz.PcbLib");
        std::fs::write(&path, &bytes).expect("write fuzz bytes");
        let _ = PcbLib::open(&path);
    }
}
